//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH_System_Patients
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NLHSystemEntities : DbContext
    {
        public NLHSystemEntities()
            : base("name=NLHSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chambre> chambres { get; set; }
        public virtual DbSet<departement> departements { get; set; }
        public virtual DbSet<docteur> docteurs { get; set; }
        public virtual DbSet<dossierAdmission> dossierAdmissions { get; set; }
        public virtual DbSet<lit> lits { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<traitement> traitements { get; set; }
        public virtual DbSet<typeChambre> typeChambres { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
    }
}
